version: "3.8"

services:
  spark:
    build: .
    volumes:
      - ./data_engineer:/data
      - ./notebook:/home/jovyan/work
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - SPARK_HOME=/usr/local/spark
      - PYSPARK_PYTHON=/opt/conda/bin/python
      - PYSPARK_DRIVER_PYTHON=jupyter
      - PYSPARK_DRIVER_PYTHON_OPTS="notebook --no-browser --port=8888 --ip=0.0.0.0 --allow-root"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CREATE_TOPICS=test_topic:1:1

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  airflow:
    image: puckel/docker-airflow:latest
    container_name: airflow
    ports:
      - "8080:8080"
    environment:
      - LOAD_EX=y
    volumes:
      - ./airflow-data:/usr/local/airflow

